import io
from datetime import date
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from fpdf import FPDF


def _term_rows(text):
    """Lines like 'Key: Value' (short keys) become table rows."""
    rows = []
    for line in text.splitlines():
        if ":" in line and len(line.split(":", 1)[0]) <= 40:
            k, v = line.split(":", 1)
            if k.strip() and v.strip():
                rows.append((k.strip(), v.strip()))
    return rows


def format_txt(text, doc_type):
    return text.encode("utf-8")


def format_docx(text, doc_type, logo_bytes=None):
    doc = Document()
    style = doc.styles["Normal"]
    style.font.name = "Times New Roman"
    style.font.size = Pt(12)

    if logo_bytes:
        doc.add_picture(io.BytesIO(logo_bytes), width=Inches(1.5))
        doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER

    title = doc.add_heading(doc_type.upper(), level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    for para in text.split("\n"):
        doc.add_paragraph(para)

    rows = _term_rows(text)
    if rows:
        doc.add_heading("Summary of Terms", level=2)
        table = doc.add_table(rows=1, cols=2, style="Table Grid")
        table.rows[0].cells[0].text, table.rows[0].cells[1].text = "Term", "Value"
        for k, v in rows:
            cells = table.add_row().cells
            cells[0].text, cells[1].text = k, v

    footer = doc.sections[0].footer.paragraphs[0]
    footer.text = f"Generated by LegalEase on {date.today():%d %b %Y}"
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def format_pdf(text, doc_type, logo_bytes=None):
    pdf = FPDF()
    pdf.add_page()
    if logo_bytes:
        with open("_logo_tmp.png", "wb") as f:
            f.write(logo_bytes)
        pdf.image("_logo_tmp.png", x=85, y=8, w=40)
        pdf.ln(30)
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, doc_type.upper(), ln=True, align="C")
    pdf.ln(4)
    pdf.set_font("Helvetica", size=11)
    safe = text.encode("latin-1", "replace").decode("latin-1")
    pdf.multi_cell(0, 6, safe)
    pdf.set_y(-15)
    pdf.set_font("Helvetica", "I", 8)
    pdf.cell(0, 10, f"Generated by LegalEase on {date.today():%d %b %Y}", align="C")
    out = pdf.output(dest="S")
    return out.encode("latin-1") if isinstance(out, str) else bytes(out)